version: "3.6"
services:
  node_a:
    build:
      context: .
      args:
        PARTY: PartyA
        RPC: 10002
        P2P: 10502
#    environment:
#      PARTY: PartyA
#      RPC_PORT: 10002
#      P2P_PORT: 10502
    stdin_open: true
    tty: true
  node_b:
    build:
      context: .
      args:
        PARTY: PartyB
        RPC: 10004
        P2P: 10504
#    environment:
#      PARTY: PartyB
#      RPC_PORT: 10004
#      P2P_PORT: 10504
    stdin_open: true
    tty: true
#  notary:
#    build:
#      context: .
#      args:
#        party: Notary
#    stdin_open: true
#    tty: true

